### ISSUE TITLE
자바스크립트 코딩의 기술 1장 정리 - 변수 할당으로 의도를 표현하라

### ISSUE THREAD

**Issue by shldhee** [Blog-Posting/posting-review#4]
# 자바스크립트 코딩의 기술 똑똑하게 코딩하는 법
- http://www.yes24.com/Product/Goods/85019231?scode=032&OzSrank=1
- 책 정리로 진행하겠습니다.
- 분량은 우선 1장하고 다시 정해볼게요

**Comment by ksy90101** [comment]
수고하셨습니다!
